# Generated by Django 5.2.3 on 2025-07-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ardapp', '0001_initial'),
    ]

   
