# Generated by Django 5.2.3 on 2025-07-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ardapp', '0002_remove_customer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
