# Generated by Django 5.2 on 2025-09-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ardapp', '0008_review_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
