# Generated by Django 5.2 on 2025-09-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ardapp', '0009_alter_customer_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
