# Generated by Django 5.2 on 2025-10-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ardapp', '0012_loader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loader',
        ),
        migrations.AddField(
            model_name='customer',
            name='meeting',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
