# Generated by Django 5.2 on 2025-10-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ardapp', '0013_delete_loader_customer_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='meeting',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
