# Generated by Django 5.2 on 2025-10-13 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ardapp', '0015_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
